### ISSUE TITLE
openvassd.conf     config_file is missing

### ISSUE THREAD

**Issue by Keskebeu** [greenbone/openvas#518] opened 2020-06-03 20:50 UTC
I installed openvas as it is described in openvas.org website. 
After issuing    openvassd -s I get that the openvassd.conf is the default directory.
config_file = /usr/local/etc/openvas/openvassd.conf

When i go to the actual folder oppenvasd.conf is not there. I recompiled the scanner from source again and noticed that openvassd.conf is not compiled during build and installation. 

Any idea?

**Comment by cfi-gb** [comment] 2020-06-04 05:05
> (optional) You may decide to change the default scanner preferences by setting them in the file $prefix/etc/openvassd.conf. If that file does not exist (default), then the default settings are used. 

https://github.com/greenbone/openvas/blob/openvas-scanner-6.0/INSTALL.md#setting-up-openvas-scanner

Closing as invalid because there is no openvassd.conf by default as explained in the documentation.

**Closed by cfi-gb** 2020-06-04 05:05 UTC
Labels: bug

**Comment by Keskebeu** [comment] 2020-06-04 20:07
@cfi-gb I have read that. Now it says that ifopenvassd.conf  does not exist  (which by default does not exist in /etc/openvas) than  says the default settings are set. 

Now I execute openvassd -s with sudo or root, and it tells me me that the openvassd.conf is in /usr/local/etc/openvas directory. Which is the default configuration for openvas. 

So my question is why does it show that a configuration file is in that folder when actually it is not?

**Comment by Keskebeu** [comment] 2020-06-04 20:12
Plus I am not a beginner in Linux to build from source. Now I also do sudo openvassd to start the scanner and nothing happens I also start gsad and and gvmd with proper configuration. What I have not tried(based on limited time) is setting up redis-server which I will end up doing later. 

So master @cfi-gb so I don't open anymore issues for the scanner. Is there any other thing that needs to be done to run openvassd? If so let me know. I would be more than happy to listen.

**Comment by cfi-gb** [comment] 2020-06-05 05:15
Please follow the advice below from https://github.com/greenbone/openvas/blob/master/.github/ISSUE_TEMPLATE/bug-report.md which should show up while creating a new issue:

> Before reporting an issue please:
>
> 1. Be aware that this is not a support forum. If your issue is rather a question than a bug report, please use our community forum at https://community.greenbone.net/c/gse instead.

**Comment by bjoernricks** [comment] 2020-06-05 07:38
I'll quote the INSTALL.md docs here
> (optional) You may decide to change the default scanner preferences by setting them in the file $prefix/etc/openvassd.conf. If that file does not exist (default), then the default settings are used. 

Means if the `$prefix/etc/openvassd.conf` can be used to change the scanner preferences but doesn't exist by default. $prefix is your install prefix which is by default `/usr/local`.

> So my question is why does it show that a configuration file is in that folder when actually it is not?

It doesn't show that a config file is in that folder. It only shows that it **would** load a config file from that folder if it exists.

**Comment by bjoernricks** [comment] 2020-06-05 07:40
So again, your request is rather a support question and not a bug in our software. Please create a topic in https://community.greenbone.net/c/gse

Also you are using an outdated and unsupported version of our software.

**Comment by Keskebeu** [comment] 2020-06-05 15:36
The bug was a clicking mistake of mine when I opened the issue and was not my intention to put it in. I understand your support and help. I installed everything fine just nothing will start when i execute everything. And I want to get this scanner running. Thank you.

**Comment by cfi-gb** [comment] 2020-06-05 16:01
I'm locking this topic as off-topic for now. If there is anything which needs to be discussed here please create a follow-up topic on https://community.greenbone.net/c/gse.

Thanks for helping to keep the communication channels between bug reports (which are handled in this repository) and support requests (which are handled in the community forums above) clean.
