### ISSUE TITLE
Issue in greenbone-nvt-sync

### ISSUE THREAD

**Issue by NitinBhasneria** [greenbone/openvas#477] opened 2020-04-11 12:00 UTC
while doing the green-nvt-sync for `ERROR: The NVT collection is very small.` But getting error 
`bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now`
This file tar.bz2 should not be deleted after the process so that we can manually extract the file.

**Comment by cfi-gb** [comment] 2020-04-11 13:12
Thanks for your report. Please have a look / a search for closed issues as well. I'm closing this as a duplicate of https://github.com/greenbone/openvas/issues/476.

Please use https://community.greenbone.net/t/community-feed-url-redirects-to-greenbone-net-nvt-sync-fails/4887 for further discussions around this topic.

**Closed by cfi-gb** 2020-04-11 13:12 UTC
Labels: bug
