### ISSUE TITLE
 openvas_scanner_connect_unix: Failed to connect to scanner

### ISSUE THREAD

**Issue by manju1920** [greenbone/openvas#541] opened 2020-07-04 08:21 UTC
Hi,
Recently I could not able to compile gvm-libs-10.0.2 on CentOS 7.8. Hence I have installed greenbone freshly on Debian GNU/Linux 10 (buster) to migrate tasks. I took backup of gvmd.db file from CentOS server and moved to Debian Server. After that I'm getting "openvas_scanner_connect_unix: Failed to connect to scanner (/var/run/openvassd.sock): No such file or directory" message and I could not start new scan.

Please help me on this.

**Comment by cfi-gb** [comment] 2020-07-04 08:33
Same as in https://github.com/greenbone/gvmd/issues/1174#issuecomment-653738908

Also a duplicate of https://github.com/greenbone/gvmd/issues/1174, if you are really facing a bug in the future please don't create multiple issues in different issue trackers.

**Closed by cfi-gb** 2020-07-04 08:33 UTC
Labels: bug
